skip_tags: true

environment:

  PYTHONPATH: "%APPVEYOR_BUILD_FOLDER%\\environment\\PYTHONPATH"
  LUCIDITY_TEMPLATE_PATH: "%APPVEYOR_BUILD_FOLDER%\\environment\\LUCIDITY_TEMPLATE_PATH"
  GITHUB_TOKEN:
    secure: ED38se1p0rp80uiNevgyn9peC7xLkHUztDjnyGhIfHe4zJavshbzHUFLHFSkVPMq

  matrix:

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install requests
  - pip install pytest
  - pip install lucidity
  - pip install git+https://github.com/PyGithub/PyGithub.git

build_script:
  - "%CMD_IN_ENV% python run_build.py"

test_script:
  - "%CMD_IN_ENV% python run_tests.py"

deploy_script:
  - "%CMD_IN_ENV% python run_deploy.py"
