environment:

  PYTHONPATH: "%APPVEYOR_BUILD_FOLDER%\\environment\\PYTHONPATH"
  LUCIDITY_TEMPLATE_PATH: "%APPVEYOR_BUILD_FOLDER%\\environment\\LUCIDITY_TEMPLATE_PATH"

  matrix:

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

build: off

branches:
  only:
    - master

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install pytest
  - pip install lucidity

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% pytest"
