name: tgbvfx-environment
channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- pip
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
  - arrow
  - riffle
- git:
  - https://bitbucket.org/ftrack/QtExt.git
  - https://bitbucket.org/ftrack/ftrack-connect.git
  - https://bitbucket.org/tokejepsen/ftrack-connect-maya.git
  - https://bitbucket.org/ftrack/ftrack-connect-nuke.git
  - https://bitbucket.org/ftrack/ftrack-connect-foundry.git
  - https://github.com/tokejepsen/ftrack-hooks.git
  - https://github.com/tokejepsen/ftrack-locations.git
  - https://github.com/tokejepsen/ftrack-template.git
  - https://github.com/tokejepsen/ftrack-connect-environment.git:
    - python $REPO_PATH/environment.py
  - https://github.com/tokejepsen/tgbvfx-environment.git:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
