name: tgbvfx-environment
channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- pip
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
- git:
  - https://bitbucket.org/tokejepsen/QtExt.git@34f785b32161d0c7006706ab5ca12763ad6d662e
  - https://bitbucket.org/ftrack/ftrack-connect.git@64b062c0b6b86ba45225878f154f0e04180cbfe1
  - https://bitbucket.org/tokejepsen/ftrack-connect-maya.git@4487fa733768a90d3a831d4570a8606c4a3d1556
  - https://github.com/tokejepsen/ftrack-hooks.git@4be9b4696416a77bfc1a91b9bc029d64cf492d99
  - https://github.com/tokejepsen/ftrack-locations.git@eccb7fca95db6d039906aa6f2da0c65f012c4838
  - https://github.com/tokejepsen/ftrack-template.git@825e29b1a81a65a38fc56f4e5b744b23a79e72df
  - https://github.com/pyblish/pyblish-base.git@6dc5781d6bb7b97fb7bc9df268f59e24a477c272
  - https://github.com/bumpybox/pyblish-bumpybox.git@3ba7d5b6de17bfc3d4b838fa62cd8c48db5d3649
  - https://github.com/tokejepsen/pyblish-ftrack.git@f9d5c7b02607ed86ded0532136b4c743581534bf
  - https://github.com/pyblish/pyblish-houdini.git@88b189a82fd6b757aa7557c1c490b97e740154a5
  - https://github.com/tokejepsen/pyblish-lite.git@543a64d4d6f6d6ce425a52b9eba8969b8e896366
  - https://github.com/pyblish/pyblish-maya.git@93651557bb62d3f367d3ec753b7b832398373888
  - https://github.com/tokejepsen/ftrack-connect-environment.git@275f7af2933b488fa2c60ef61ab1984be389714c:
    - python $REPO_PATH/environment.py
  - https://github.com/tokejepsen/tgbvfx-environment.git:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
