channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- pip
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
  - arrow
  - riffle
  - git+https://github.com/pyqt/python-qt5.git#egg=python-qt5
- git:
  - https://bitbucket.org/thegentlemenbroncos/tgbvfx-pipeline.git@0af96a4890f298a3100b53d30deb58e5b73a394e
  - https://github.com/pyblish/pyblish-base.git@437234e6bb59b50763a388f8d411b558f9203701
  - https://github.com/pyblish/pyblish-qml.git@7140f6c4bfc28481e902929d9a39f7ebc8d5a24f
  - https://github.com/tokejepsen/pyblish-nukestudio.git@812e945a455a9e13877841436379bcd4f8fa42e3
  - https://github.com/pyblish/pyblish-ftrack.git@ad33c34bf4eea2e776554667502421bc9e5986c6
  - https://github.com/bumpybox/pyblish-bumpybox.git@d4146ef95850919f3c4224ab283d6dbe756cab71
  - https://bitbucket.org/ftrack/ftrack-python-legacy-api.git@97cb35a6ae98958f95e61a7925701d9e8eea375d
  - https://bitbucket.org/ftrack/ftrack-connect.git@d0c31457b23e41701bcf88d9baeb723de4affbc1
  - https://bitbucket.org/ftrack/ftrack-connect-maya.git@23c7ffa6ee97e8032180246a585428d09c474ea3
  - https://bitbucket.org/ftrack/ftrack-connect-nuke.git@d1b8a32bfddf71541b8ccd954198b7adda674792
  - https://bitbucket.org/ftrack/ftrack-connect-foundry.git@7cf86f01faf983c6f094dd86cda8ecdd7417cf3e
  - https://bitbucket.org/ftrack/ftrack-connect-rv.git@a1810c5309312c3aa4aa7855beeda44ee798c279
  - https://bitbucket.org/ftrack/ftrack-connect-nuke-studio.git@d97733435037c54a7d091df3f4ecafef11d41b03
  - https://github.com/tokejepsen/ftrack-hooks.git@7d28fdbba4ab701fbd9c3b50ed6bd179824ea9b9
  - https://github.com/tokejepsen/ftrack-connect-environment.git@fa51c5d0d4cc386dd124cbb6a814087583d07c3f:
    - python $REPO_PATH/environment.py
  - https://github.com/tokejepsen/pyblish-grill-environment.git@3488a8aa32a8375c6695cefcc35ee670b2a883e8:
    - python $REPO_PATH/environment.py
  - https://github.com/tokejepsen/tgbvfx-environment.git@0db45ba2709bc4ee226a2b36fd018dab3dcad248:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
name: tgbvfx-environment
