dependencies:
- python=2.7
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
  - arrow
  - riffle
  - git+https://github.com/pyqt/python-qt5.git#python-qt5
  - psutil
- git:
  - https://github.com/tokejepsen/filelink.git@01c782e4ce8043914cc09908392747954f5284b1
  - https://bitbucket.org/thegentlemenbroncos/tgbvfx-pipeline.git@bbd35be7dcb286e7471e543c1e36f05f14faea96
  - https://github.com/pyblish/pyblish-base.git@477f540981433867aa219cc46cd0fa5890ecf17c
  - https://github.com/pyblish/pyblish-qml.git@2a91bae3785b22a826d3826264eac375f186ed35
  - https://github.com/pyblish/pyblish-nukestudio.git@225b2af344468fa43c51a14f71a512b8a317cb48
  - https://github.com/pyblish/pyblish-ftrack.git@ff2a1f273920f2e94588fd5f93da38b6f221d8c6
  - https://github.com/pyblish/pyblish-nuke.git@d896c2b6634c571abbbe78c15bf1baf23078d05d
  - https://github.com/pyblish/pyblish-royalrender.git@d7c83ee8c49295f9a514cd3917f7323bd54b18ea
  - https://github.com/bumpybox/pyblish-bumpybox.git@bc1e12b32a45a6e7074e4531c7bbca551ed7d5c3
  - https://bitbucket.org/ftrack/ftrack-python-legacy-api.git@97cb35a6ae98958f95e61a7925701d9e8eea375d
  - https://bitbucket.org/ftrack/ftrack-connect.git@f2d816b4f2910dd6713f18ecb1c79a83ae50c778
  - https://bitbucket.org/ftrack/ftrack-connect-maya.git@23c7ffa6ee97e8032180246a585428d09c474ea3
  - https://bitbucket.org/ftrack/ftrack-connect-nuke.git@d1b8a32bfddf71541b8ccd954198b7adda674792
  - https://bitbucket.org/ftrack/ftrack-connect-foundry.git@7cf86f01faf983c6f094dd86cda8ecdd7417cf3e
  - https://bitbucket.org/ftrack/ftrack-connect-rv.git@a1810c5309312c3aa4aa7855beeda44ee798c279
  - https://bitbucket.org/ftrack/ftrack-connect-nuke-studio.git@d97733435037c54a7d091df3f4ecafef11d41b03
  - https://github.com/bumpybox/ftrack-hooks.git@668b08b2c23eefd2df56f4829de36d284237fc62
  - https://github.com/tokejepsen/ftrack-connect-environment.git@6325d37527c0e6b44b94c518b49a1ab828d71dd1:
    - python $REPO_PATH/environment.py
  - https://github.com/tokejepsen/pyblish-grill-environment.git@a135d58102eede129455938dd7c79a55a969592f:
    - python $REPO_PATH/environment.py
  - https://github.com/tokejepsen/tgbvfx-environment.git:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
name: tgbvfx-environment
