name: tgbvfx-core
dependencies:
- python=2.7
- git:
  - https://github.com/tokejepsen/tgbvfx-core.git:
    - python $REPO_PATH/environment.py
  - https://github.com/Bumpybox/bumpybox-core.git:
    - python $REPO_PATH/startup.py
