channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- pip
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
  - arrow
  - riffle
- git:
  - https://github.com/pyblish/pyblish-base.git@9a3d78772f73e5905c131f9431cc3a266b23cbf7
  - https://github.com/pyblish/pyblish-lite.git@b50a7fc9b755c7986d88b06e17cf5494097cefa0
  - https://github.com/pyblish/pyblish-standalone.git@0f279c0e08f4c99bd6e5ef954452835e01e2ee61
  - https://github.com/pyblish/pyblish-maya.git@b81e6edd67e9969348a133c8a6e630ab92fd6c3f
  - https://github.com/tokejepsen/pyblish-nuke.git@14fa2848814c1655317067af9a158f10de99ed68
  - https://github.com/pyblish/pyblish-ftrack.git@335eb84240a5e00b883003fd255cf5fc7a6d06f6
  - https://github.com/pyblish/pyblish-royalrender.git@00be932cc01eb18b7456c2b54ab4ee9345fe6ebc
  - https://github.com/bumpybox/pyblish-bumpybox.git@618496fc45b195cc55e0be4ea8934fd2f3371bc3
  - https://bitbucket.org/ftrack/QtExt.git@f88d1db8d5b7a0f5162f29a0701166d3be24fd19
  - https://bitbucket.org/ftrack/ftrack-connect.git@0354ecb0d32e6cd6ad54d9787d16549606d7d6e1
  - https://bitbucket.org/tokejepsen/ftrack-connect-maya.git@a3357544ab4986f7fcab45b05b74e669d987ea1f
  - https://bitbucket.org/ftrack/ftrack-connect-nuke.git@74ea5d8ba0589256b035a375152641ed9c6c9376
  - https://bitbucket.org/ftrack/ftrack-connect-foundry.git@4a5323c453855ff909b7ba6b7ce8ac43617977a2
  - https://bitbucket.org/ftrack/ftrack-connect-rv.git@37fc722cd1c6ff3bbc473ee12a74ba61a7d8d2a9
  - https://github.com/tokejepsen/ftrack-hooks.git@129a010fba0fd39fa146261d1d73f8b3d2380718
  - https://github.com/tokejepsen/ftrack-locations.git@eccb7fca95db6d039906aa6f2da0c65f012c4838
  - https://github.com/tokejepsen/ftrack-template.git@825e29b1a81a65a38fc56f4e5b744b23a79e72df
  - https://github.com/tokejepsen/ftrack-connect-environment.git@3c71b345f1732979364b27b714f898a43ddc20a6:
    - python $REPO_PATH/environment.py
  - https://github.com/tokejepsen/tgbvfx-environment.git:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
name: tgbvfx-environment
