
################################## Submitter Settings ################################## 
SceneFileExtension= *.ma;*.mb
AllowImageNameChange= 0
AllowImageDirChange= 0
Priority= 1~10
SeqDivMIN= 1~1
SeqDivMAX= 1~1
DoNotCheckForFrames= 0~1
DoNotShowPreviewJpegs= 0~1
Overwriteexistingfiles= 0~1
AllowLocalSceneCopy= 0~0
AllowLocalRenderOut= 0~0
KeepSceneOpen= 0~0
RenderPreviewFirst= 0~0
PPSequenceCheck= 0~0
PPCreateSmallVideo= 0~0
SequenceDivide= 0~1
UIStyle= 1~dark

################################## Client Settings ################################## 

Frozen_MinCoreUsage=1.90

TexReplaceFormat= .ma ~ Char ~ AlwaysForward
TexReplaceFormat= .mb ~ FOR4 ~ AlwaysForward

licenseFailLine=  No license suitable to run
licenseFailLine=  License was not obtained
licenseFailLine=  could not get a license
licenseFailLine=  can't find any valid product licenses

errorSearchLine=  Error reported, aborting render script
errorSearchLine=  unable to open file
errorSearchLine=  V-Ray: Render interrupted

permanentErrorSearchLine = Unknown Maya file version
permanentErrorSearchLine = Cannot open renderer description file
permanentErrorSearchLine = Cannot render
permanentErrorSearchLine = rrMaya - ERR
permanentErrorSearchLine = Invalid flag
permanentErrorSearchLine = Requested layer does not exist!


findFrameNoPre= Frame #
findFrameNoPost=  done


RenderAppWindow_WIN= Error ~ Unable to locate valid MAYA_APP_DIR ~ 1 ~ Button ~ OK 
RenderAppWindow_WIN= Browse for Folder ~ Select a directory where Maya will store user data ~ 1 ~ Button ~ Cancel 
RenderAppWindow_WIN= Warning ~ Cannot run Maya without a valid setting for MAYA_APP_DIR ~ 1 ~ Button ~ &No

